#line 2 "lexico_lienzo.cpp"

#line 4 "lexico_lienzo.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer lienzo_create_buffer
#define yy_delete_buffer lienzo_delete_buffer
#define yy_flex_debug lienzo_flex_debug
#define yy_init_buffer lienzo_init_buffer
#define yy_flush_buffer lienzo_flush_buffer
#define yy_load_buffer_state lienzo_load_buffer_state
#define yy_switch_to_buffer lienzo_switch_to_buffer
#define yyin lienzoin
#define yyleng lienzoleng
#define yylex lienzolex
#define yylineno lienzolineno
#define yyout lienzoout
#define yyrestart lienzorestart
#define yytext lienzotext
#define yywrap lienzowrap
#define yyalloc lienzoalloc
#define yyrealloc lienzorealloc
#define yyfree lienzofree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE lienzorestart(lienzoin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int lienzoleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *lienzoin, *lienzoout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lienzotext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up lienzotext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via lienzorestart()), so that the user can continue scanning by
	 * just pointing lienzoin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when lienzotext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int lienzoleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow lienzowrap()'s to do buffer switches
 * instead of setting up a fresh lienzoin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void lienzorestart (FILE *input_file  );
void lienzo_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE lienzo_create_buffer (FILE *file,int size  );
void lienzo_delete_buffer (YY_BUFFER_STATE b  );
void lienzo_flush_buffer (YY_BUFFER_STATE b  );
void lienzopush_buffer_state (YY_BUFFER_STATE new_buffer  );
void lienzopop_buffer_state (void );

static void lienzoensure_buffer_stack (void );
static void lienzo_load_buffer_state (void );
static void lienzo_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER lienzo_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE lienzo_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE lienzo_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE lienzo_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *lienzoalloc (yy_size_t  );
void *lienzorealloc (void *,yy_size_t  );
void lienzofree (void *  );

#define yy_new_buffer lienzo_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        lienzoensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lienzo_create_buffer(lienzoin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        lienzoensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lienzo_create_buffer(lienzoin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] lienzotext/lienzoin/lienzoout/yy_state_type/lienzolineno etc. def's & init go here */
/* Begin user sect3 */

#define lienzowrap(n) 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *lienzoin = (FILE *) 0, *lienzoout = (FILE *) 0;

typedef int yy_state_type;

extern int lienzolineno;

int lienzolineno = 1;

extern char *lienzotext;
#define yytext_ptr lienzotext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up lienzotext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle lienzotext and lienzoleng for yymore() goes here \ */\
	lienzoleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to lienzotext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,   85,   83,   81,   82,   56,   83,   31,   83,
       83,   41,   42,   59,   57,   35,   58,   60,   74,   43,
       32,   46,   36,   47,   34,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   37,   38,   61,   39,   83,   40,   83,   81,
        0,   45,    0,    0,   77,    0,   52,   55,    0,    0,
       62,   64,   63,   65,    0,   74,    0,   48,   44,   49,
       79,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,    9,   78,   78,   78,   78,   51,   33,

       53,    0,   54,   77,    0,    0,    0,    0,    0,    0,
        0,   76,   76,   75,    0,    0,   79,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,    6,   78,   50,   80,
       78,   78,   78,   78,   78,   12,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       16,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       10,   78,   72,   66,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   68,   78,   78,   73,   18,   78,

       78,   78,   78,   27,   78,   78,   78,   78,   78,   78,
       78,   14,   78,   78,   78,   78,   69,   78,   78,   78,
       78,   78,   78,   67,   78,   78,    1,   78,   78,   78,
       29,   78,   78,   78,   78,   78,   78,    8,   78,   70,
       78,   78,   78,   78,   13,   78,   78,   28,   78,   24,
       78,   78,    4,   78,    3,   19,   78,   78,   71,   78,
       78,   78,   78,    2,   17,   78,   20,   22,   78,   78,
       78,   78,   11,    7,   15,   78,   21,   23,    5,   30,
       25,   78,   26,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   33,   44,   33,   45,
       46,   47,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   33,   33,   60,   61,   62,
       63,   64,   33,   65,   66,   67,   68,   69,   33,   70,
       33,   71,   72,   73,   74,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       75,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       76,    1,    1,   77,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    3,    3,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[290] =
    {   0,
        0,    0,  292,  576,  268,  576,   71,   74,  576,   73,
      214,  576,  576,  576,   69,  576,   68,  576,   68,  576,
      576,   70,  234,   65,  576,   54,   51,   71,   68,   62,
       75,    0,   76,   67,   71,   77,   68,  111,   82,  115,
       73,  105,  576,  576,  576,  576,  178,  576,  174,  247,
       90,  576,  172,  108,  576,  179,  576,  576,  232,  192,
      576,  576,  576,  576,  176,  100,  146,  576,  576,  576,
        0,    0,   86,   92,  112,  132,  128,  125,  133,  111,
      120,  139,  143,  139,  152,  154,  165,  149,  165,  173,
      169,  161,  177,  176,  178,  174,  178,  174,  576,  576,

      576,   73,  576,  217,  218,  219,  220,  224,  225,  229,
      272,  576,  133,  123,  102,   89,    0,  219,  220,  218,
      225,  230,  219,  219,  218,  232,  236,  234,  235,  237,
      233,  251,  267,  250,  259,  265,  274,  259,  274,  263,
      271,  270,  282,  279,  298,  295,    0,  300,  576,  576,
      302,  302,  312,  308,  319,    0,  308,  320,  319,  326,
      325,  327,  318,  330,  332,  323,  324,  320,  325,  332,
        0,  329,  347,  337,  350,  353,  353,  352,  347,  351,
        0,  354,    0,    0,  362,  370,  375,  377,  364,  369,
      368,  373,  369,  377,    0,  377,  379,    0,    0,  374,

      380,  379,  396,    0,  384,  385,  389,  400,  400,  408,
      401,    0,  406,  405,  417,  414,    0,  418,  427,  412,
      414,  421,  426,    0,  432,  422,    0,  436,  425,   54,
        0,  428,  430,  437,  434,  450,  432,    0,  442,    0,
      444,  451,  461,  465,    0,  463,  466,    0,  458,    0,
      468,  471,    0,  472,    0,    0,  476,  466,    0,  471,
      472,  474,  478,    0,    0,  476,    0,    0,  483,  482,
      481,  495,    0,    0,    0,  484,    0,    0,    0,    0,
        0,  500,    0,  576,  555,  560,   96,  565,  570
    } ;

static yyconst flex_int16_t yy_def[290] =
    {   0,
      284,    1,  284,  284,  284,  284,  284,  285,  284,  284,
      286,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  285,  284,  285,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  288,  284,  284,  284,
      289,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  284,  284,

      284,  284,  284,  285,  285,  285,  285,  285,  285,  285,
      285,  284,  284,  284,  288,  284,  289,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  284,  284,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,    0,  284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_nxt[654] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,    4,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   32,   35,   36,   32,   37,   38,   39,   40,
       41,   32,   42,   32,   32,   43,    4,   44,   45,    4,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   32,   37,   38,   39,   40,   41,   32,   42,   32,
       32,   46,   47,   48,    4,    4,   49,   51,   55,   57,
       61,   63,   65,   67,   66,   70,   71,   75,   64,   62,
       68,   52,   73,   74,   76,   78,  101,   80,   82,   83,

       72,   84,   85,  251,   79,   81,   87,   77,   86,   92,
      150,   96,   55,   75,   65,  116,   66,  119,   73,   74,
       56,   76,   78,   80,  118,   82,   83,   84,   97,   85,
       79,   81,   87,   77,   88,   86,   92,   96,   93,  114,
      112,   98,   89,   53,  119,   58,   94,  149,  120,   90,
      118,  129,   91,  126,   56,   97,   95,  128,  121,  116,
      130,   88,  124,  125,  127,   93,  102,   98,  132,   89,
      122,  123,  131,   94,  120,   90,  133,  129,   91,  134,
      126,  135,   95,  104,  128,  121,  130,  137,  124,  125,
      127,  136,  114,  141,  105,  132,  122,  123,  131,  113,

      138,  142,  133,  106,  139,  148,  134,  107,  135,  140,
      143,  144,  145,  137,  108,  146,  147,  109,  136,  110,
      141,   55,   55,   55,   55,  111,  138,  142,   55,   55,
      106,  139,  148,   55,  107,  140,  143,  144,  145,  112,
      108,  146,  147,  109,  103,  110,  151,  152,   50,  100,
       99,  153,  154,  155,   69,  156,  157,  158,  159,  160,
       60,  161,  163,   56,   56,   56,   56,  162,  164,   50,
       56,   56,  165,  151,  152,   56,  104,  153,  166,  154,
      155,  156,  157,  158,  159,  168,  160,  105,  161,  163,
      167,  284,  170,  162,  169,  164,  106,  171,  165,  173,

      107,  172,  284,  177,  178,  166,  179,  108,  174,  175,
      109,  168,  110,  180,  284,  181,  176,  167,  111,  170,
      169,  182,  183,  106,  171,  173,  184,  107,  172,  177,
      178,  185,  179,  108,  174,  175,  109,  186,  110,  187,
      180,  181,  176,  188,  189,  284,  190,  191,  182,  183,
      192,  193,  194,  184,  195,  284,  196,  197,  185,  198,
      284,  199,  200,  186,  201,  202,  187,  203,  204,  188,
      205,  189,  190,  206,  191,  207,  208,  192,  193,  194,
      209,  195,  196,  210,  197,  211,  198,  199,  200,  212,
      201,  202,  213,  203,  204,  214,  215,  205,  216,  206,

      217,  226,  207,  208,  218,  219,  220,  209,  221,  222,
      210,  211,  223,  224,  225,  212,  227,  228,  213,  229,
      232,  214,  230,  215,  231,  216,  233,  217,  226,  234,
      218,  219,  220,  235,  221,  222,  236,  237,  223,  224,
      225,  238,  227,  228,  239,  241,  229,  232,  230,  240,
      231,  242,  246,  233,  243,  244,  234,  245,  247,  249,
      235,  248,  236,  250,  237,  252,  253,  238,  254,  284,
      255,  239,  241,  256,  260,  240,  257,  258,  242,  246,
      243,  244,  259,  245,  261,  247,  249,  248,  262,  250,
      263,  252,  253,  264,  269,  254,  255,  265,  270,  271,

      256,  260,  257,  258,  266,  267,  272,  268,  259,  273,
      274,  261,  275,  276,  277,  262,  278,  263,  279,  280,
      264,  269,  281,  265,  282,  270,  271,  283,  284,  284,
      266,  267,  272,  268,  284,  273,  274,  284,  275,  276,
      277,  284,  278,  284,  279,  280,  284,  284,  284,  281,
      282,  284,  284,  284,  283,   54,  284,   54,   54,   54,
       59,  284,   59,  284,   59,  115,  115,  284,  115,  115,
      117,  284,  117,  117,  117,    3,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[654] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,   10,
       15,   17,   19,   22,   19,   24,   24,   27,   17,   15,
       22,    7,   26,   26,   28,   29,   51,   30,   31,   33,

      287,   34,   35,  230,   29,   30,   37,   28,   36,   39,
      116,   41,   54,   27,   66,  115,   66,   74,   26,   26,
        8,   28,   29,   30,   73,   31,   33,   34,   42,   35,
       29,   30,   37,   28,   38,   36,   39,   41,   40,  114,
      113,   42,   38,    7,   74,   10,   40,  102,   75,   38,
       73,   80,   38,   78,   54,   42,   40,   79,   76,   67,
       81,   38,   77,   77,   78,   40,   51,   42,   83,   38,
       76,   76,   82,   40,   75,   38,   84,   80,   38,   85,
       78,   86,   40,   56,   79,   76,   81,   88,   77,   77,
       78,   87,   65,   91,   56,   83,   76,   76,   82,   60,

       89,   92,   84,   56,   90,   98,   85,   56,   86,   90,
       93,   94,   95,   88,   56,   96,   97,   56,   87,   56,
       91,  104,  105,  106,  107,   56,   89,   92,  108,  109,
       56,   90,   98,  110,   56,   90,   93,   94,   95,   59,
       56,   96,   97,   56,   53,   56,  118,  119,   50,   49,
       47,  120,  121,  122,   23,  123,  124,  125,  125,  126,
       11,  127,  129,  104,  105,  106,  107,  128,  130,    5,
      108,  109,  131,  118,  119,  110,  111,  120,  132,  121,
      122,  123,  124,  125,  125,  134,  126,  111,  127,  129,
      133,    3,  136,  128,  135,  130,  111,  137,  131,  138,

      111,  137,    0,  140,  141,  132,  142,  111,  139,  139,
      111,  134,  111,  143,    0,  144,  139,  133,  111,  136,
      135,  145,  146,  111,  137,  138,  148,  111,  137,  140,
      141,  151,  142,  111,  139,  139,  111,  152,  111,  153,
      143,  144,  139,  154,  155,    0,  157,  158,  145,  146,
      159,  160,  161,  148,  162,    0,  163,  164,  151,  165,
        0,  166,  167,  152,  168,  169,  153,  170,  172,  154,
      173,  155,  157,  174,  158,  175,  176,  159,  160,  161,
      177,  162,  163,  178,  164,  179,  165,  166,  167,  180,
      168,  169,  182,  170,  172,  185,  186,  173,  187,  174,

      188,  200,  175,  176,  189,  190,  191,  177,  192,  193,
      178,  179,  194,  196,  197,  180,  201,  202,  182,  203,
      207,  185,  205,  186,  206,  187,  208,  188,  200,  209,
      189,  190,  191,  210,  192,  193,  211,  213,  194,  196,
      197,  214,  201,  202,  215,  218,  203,  207,  205,  216,
      206,  219,  223,  208,  220,  221,  209,  222,  225,  228,
      210,  226,  211,  229,  213,  232,  233,  214,  234,    0,
      235,  215,  218,  236,  242,  216,  237,  239,  219,  223,
      220,  221,  241,  222,  243,  225,  228,  226,  244,  229,
      246,  232,  233,  247,  252,  234,  235,  249,  254,  257,

      236,  242,  237,  239,  251,  251,  258,  251,  241,  260,
      261,  243,  262,  263,  266,  244,  269,  246,  270,  271,
      247,  252,  272,  249,  276,  254,  257,  282,    0,    0,
      251,  251,  258,  251,    0,  260,  261,    0,  262,  263,
      266,    0,  269,    0,  270,  271,    0,    0,    0,  272,
      276,    0,    0,    0,  282,  285,    0,  285,  285,  285,
      286,    0,  286,    0,  286,  288,  288,    0,  288,  288,
      289,    0,  289,  289,  289,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int lienzo_flex_debug;
int lienzo_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[84] =
    {   0,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   66,   67,   68,   69,   70,   71,   72,
       74,   75,   76,   77,   78,   79,   81,   82,   83,   84,
       85,   86,   87,   88,   89,   91,   92,   93,   94,   95,
       96,   98,  103,  108,  113,  118,  124,  132,  137,  138,
      139,  140,  142
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *lienzotext;
#line 1 "lexico_lienzo.l"
#line 4 "lexico_lienzo.l"
#include <stdio.h>
#include <stdlib.h>
#include "sintactico_lienzo.h"
int lienzoline = 1;
/*--------------------------------------------------------------------------
 *	Tokens definidos por ER
 *--------------------------------------------------------------------------*/
#line 823 "lexico_lienzo.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int lienzolex_destroy (void );

int lienzoget_debug (void );

void lienzoset_debug (int debug_flag  );

YY_EXTRA_TYPE lienzoget_extra (void );

void lienzoset_extra (YY_EXTRA_TYPE user_defined  );

FILE *lienzoget_in (void );

void lienzoset_in  (FILE * in_str  );

FILE *lienzoget_out (void );

void lienzoset_out  (FILE * out_str  );

int lienzoget_leng (void );

char *lienzoget_text (void );

int lienzoget_lineno (void );

void lienzoset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int lienzowrap (void );
#else
extern int lienzowrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( lienzotext, lienzoleng, 1, lienzoout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( lienzoin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( lienzoin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, lienzoin))==0 && ferror(lienzoin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(lienzoin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int lienzolex (void);

#define YY_DECL int lienzolex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after lienzotext and lienzoleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 19 "lexico_lienzo.l"


#line 1073 "lexico_lienzo.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! lienzoin )
/* %if-c-only */
			lienzoin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! lienzoout )
/* %if-c-only */
			lienzoout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			lienzoensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				lienzo_create_buffer(lienzoin,YY_BUF_SIZE );
		}

		lienzo_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of lienzotext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 576 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for lienzolineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( lienzo_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 84 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], lienzotext );
			else if ( yy_act == 84 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         lienzotext );
			else if ( yy_act == 85 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "lexico_lienzo.l"
{ return(LIENZO); };
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "lexico_lienzo.l"
{ return(EXTIENDE); };
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "lexico_lienzo.l"
{ return(PUBLICO); };
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "lexico_lienzo.l"
{ return(PRIVADO); };
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "lexico_lienzo.l"
{ return(PROTEGIDO); };
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "lexico_lienzo.l"
{ return(VAR); };
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "lexico_lienzo.l"
{ return(CONSERVAR); };
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "lexico_lienzo.l"
{ return(ARR); };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "lexico_lienzo.l"
{ return(SI); };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "lexico_lienzo.l"
{ return(SINO); };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "lexico_lienzo.l"
{ return(COMPROBAR); };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "lexico_lienzo.l"
{ return(CASO); };
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "lexico_lienzo.l"
{ return(DEFECTO); };
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "lexico_lienzo.l"
{ return(SALIR); };
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "lexico_lienzo.l"
{ return(CONTINUAR); };
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "lexico_lienzo.l"
{ return(PARA); };
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "lexico_lienzo.l"
{ return(MIENTRAS); };
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "lexico_lienzo.l"
{ return(HACER); };
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "lexico_lienzo.l"
{ return(RETORNA); };
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "lexico_lienzo.l"
{ return(PINTAR_P); };
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "lexico_lienzo.l"
{ return(PINTAR_OR); };
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "lexico_lienzo.l"
{ return(PINTAR_S); };
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "lexico_lienzo.l"
{ return(PRINCIPAL); };
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "lexico_lienzo.l"
{ return(ORDENAR); };
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "lexico_lienzo.l"
{ return(ASC); };
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "lexico_lienzo.l"
{ return(DESC); };
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "lexico_lienzo.l"
{ return(PAR); };
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "lexico_lienzo.l"
{ return(IMPAR); };
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "lexico_lienzo.l"
{ return(PRIMO); };
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "lexico_lienzo.l"
{ return(SUMARIZAR); };
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "lexico_lienzo.l"
{ return(FIN); };
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "lexico_lienzo.l"
{ return(PYC); };
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "lexico_lienzo.l"
{ return(OPEN); };
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "lexico_lienzo.l"
{ return(CLOSE); };
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "lexico_lienzo.l"
{ return(COMA); };
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "lexico_lienzo.l"
{ return(ASIG); };
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "lexico_lienzo.l"
{ return(C_OPEN); };
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "lexico_lienzo.l"
{ return(C_CLOSE); };
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "lexico_lienzo.l"
{ return(LL_OPEN); };
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "lexico_lienzo.l"
{ return(LL_CLOSE); };
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "lexico_lienzo.l"
{ return(P_OPEN); };
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "lexico_lienzo.l"
{ return(P_CLOSE); };
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "lexico_lienzo.l"
{ return(DANGOS); };
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "lexico_lienzo.l"
{ return(IGUAL); };
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "lexico_lienzo.l"
{ return(DIFERENTE); };
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "lexico_lienzo.l"
{ return(MEN); };
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 69 "lexico_lienzo.l"
{ return(MAY); };
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 70 "lexico_lienzo.l"
{ return(MEN_IGUAL); };
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 71 "lexico_lienzo.l"
{ return(MAY_IGUAL); };
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "lexico_lienzo.l"
{ return(NULO); };
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "lexico_lienzo.l"
{ return(OR); };
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "lexico_lienzo.l"
{ return(AND); };
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "lexico_lienzo.l"
{ return(NAND); };
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "lexico_lienzo.l"
{ return(NOR); };
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "lexico_lienzo.l"
{ return(XOR); };
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "lexico_lienzo.l"
{ return(NOT); };
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 "lexico_lienzo.l"
{ return(SUM); };
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 "lexico_lienzo.l"
{ return(SUB); };
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 "lexico_lienzo.l"
{ return(MUL); };
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 "lexico_lienzo.l"
{ return(DIV); };
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 85 "lexico_lienzo.l"
{ return(POW); };
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 86 "lexico_lienzo.l"
{ return(INCREMENTO); };
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 87 "lexico_lienzo.l"
{ return(DECREMENTO); };
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 88 "lexico_lienzo.l"
{ return(SUM_SIMPLY); };
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 89 "lexico_lienzo.l"
{ return(SUB_SIMPLY); };
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "lexico_lienzo.l"
{ return(T_VOID); };
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "lexico_lienzo.l"
{ return(T_ENTERO); };
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "lexico_lienzo.l"
{ return(T_DOBLE); };
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "lexico_lienzo.l"
{ return(T_CADENA); };
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 95 "lexico_lienzo.l"
{ return(T_BOOLEAN); };
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 96 "lexico_lienzo.l"
{ return(T_CARACTER); };
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "lexico_lienzo.l"
{
    lienzolval.CADENA = new QString(lienzotext);
    return(TRUE);
};
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 103 "lexico_lienzo.l"
{
    lienzolval.CADENA = new QString(lienzotext);
    return(FALSE);
};
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "lexico_lienzo.l"
{
    lienzolval.CADENA = new QString(lienzotext);
    return(ENTERO);
};
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "lexico_lienzo.l"
{
    lienzolval.CADENA = new QString(lienzotext);
    return(DOBLE);
};
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "lexico_lienzo.l"
{
    QString aux = QString(lienzotext);
    lienzolval.CADENA = new QString(aux.mid(1,aux.length()-2));
    return(CARACTER);
};
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "lexico_lienzo.l"
{
    QString aux = QString(lienzotext);
    aux = aux.replace("\\n","\n");
    aux = aux.replace("\\t","\t");
    lienzolval.CADENA = new QString(aux.mid(1,aux.length()-2));
    return(CADENA);
};
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 132 "lexico_lienzo.l"
{
    lienzolval.CADENA = new QString(lienzotext);
    return(ID);
};
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 137 "lexico_lienzo.l"
{ /* comentario de una línea */ } ;
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 138 "lexico_lienzo.l"
{ /* comentarios multilínea*/ }; 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 139 "lexico_lienzo.l"
{ /* espacios en blanco */ }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 140 "lexico_lienzo.l"
{ lienzoline++; }; 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 142 "lexico_lienzo.l"
{ fprintf(stderr, "Error léxico '%s' en la línea %d\n", lienzotext, lienzoline); };
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 144 "lexico_lienzo.l"
ECHO;
	YY_BREAK
#line 1634 "lexico_lienzo.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed lienzoin at a new source and called
			 * lienzolex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = lienzoin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( lienzowrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * lienzotext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of lienzolex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					lienzorealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			lienzorestart(lienzoin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) lienzorealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up lienzotext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update lienzolineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					lienzorestart(lienzoin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( lienzowrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve lienzotext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and lienzolineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void lienzorestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        lienzoensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            lienzo_create_buffer(lienzoin,YY_BUF_SIZE );
	}

	lienzo_init_buffer(YY_CURRENT_BUFFER,input_file );
	lienzo_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void lienzo_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		lienzopop_buffer_state();
	 *		lienzopush_buffer_state(new_buffer);
     */
	lienzoensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	lienzo_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (lienzowrap()) processing, but the only time this flag
	 * is looked at is after lienzowrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void lienzo_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	lienzoin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE lienzo_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) lienzoalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lienzo_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) lienzoalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in lienzo_create_buffer()" );

	b->yy_is_our_buffer = 1;

	lienzo_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with lienzo_create_buffer()
 * 
 */
/* %if-c-only */
    void lienzo_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		lienzofree((void *) b->yy_ch_buf  );

	lienzofree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a lienzorestart() or at EOF.
 */
/* %if-c-only */
    static void lienzo_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	lienzo_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then lienzo_init_buffer was _probably_
     * called from lienzorestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void lienzo_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		lienzo_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void lienzopush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	lienzoensure_buffer_stack();

	/* This block is copied from lienzo_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from lienzo_switch_to_buffer. */
	lienzo_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void lienzopop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	lienzo_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		lienzo_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void lienzoensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)lienzoalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lienzoensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)lienzorealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lienzoensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE lienzo_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) lienzoalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lienzo_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	lienzo_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to lienzolex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       lienzo_scan_bytes() instead.
 */
YY_BUFFER_STATE lienzo_scan_string (yyconst char * yystr )
{
    
	return lienzo_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to lienzolex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE lienzo_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) lienzoalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in lienzo_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = lienzo_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in lienzo_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lienzotext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		lienzotext[lienzoleng] = (yy_hold_char); \
		(yy_c_buf_p) = lienzotext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		lienzoleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int lienzoget_lineno  (void)
{
        
    return lienzolineno;
}

/** Get the input stream.
 * 
 */
FILE *lienzoget_in  (void)
{
        return lienzoin;
}

/** Get the output stream.
 * 
 */
FILE *lienzoget_out  (void)
{
        return lienzoout;
}

/** Get the length of the current token.
 * 
 */
int lienzoget_leng  (void)
{
        return lienzoleng;
}

/** Get the current token.
 * 
 */

char *lienzoget_text  (void)
{
        return lienzotext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void lienzoset_lineno (int  line_number )
{
    
    lienzolineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see lienzo_switch_to_buffer
 */
void lienzoset_in (FILE *  in_str )
{
        lienzoin = in_str ;
}

void lienzoset_out (FILE *  out_str )
{
        lienzoout = out_str ;
}

int lienzoget_debug  (void)
{
        return lienzo_flex_debug;
}

void lienzoset_debug (int  bdebug )
{
        lienzo_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from lienzolex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    lienzoin = stdin;
    lienzoout = stdout;
#else
    lienzoin = (FILE *) 0;
    lienzoout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * lienzolex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* lienzolex_destroy is for both reentrant and non-reentrant scanners. */
int lienzolex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		lienzo_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		lienzopop_buffer_state();
	}

	/* Destroy the stack itself. */
	lienzofree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * lienzolex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *lienzoalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *lienzorealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void lienzofree (void * ptr )
{
	free( (char *) ptr );	/* see lienzorealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 144 "lexico_lienzo.l"




